global using static System.Net.Mime.MediaTypeNames;
global using Microsoft.EntityFrameworkCore;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.Rendering;
global using System.ComponentModel.DataAnnotations;
global using Microsoft.AspNetCore.Mvc.ModelBinding.Validation;
global using Tech_Mart;
global using Tech_Mart.Data;
global using Tech_Mart.Models;
global using Tech_Mart.Controllers;
global using Tech_Mart.Areas;
global using Tech_Mart.Settings;
